### ISSUE TITLE
How does "sparse blossom" compare to Blossom V

### ISSUE THREAD

**Issue by qodesign** [oscarhiggott/PyMatching#106]
Is there a way to benchmark the two implementations on a common test input?

Blossom V is available here for non-commercial use : https://pub.ista.ac.at/~vnk/software.html#BLOSSOM5
There's an example included but it uses a very small graph ("GRAPH1.txt"). It would be good to be able to define
a more substantial example graph with some way to test it with both Blossom V and sparse blossom.

**Comment by oscarhiggott** [comment]
Sparse blossom and Blossom V solve slightly different problems. Sparse blossom solves the matching QEC decoding problem, also known the embedded matching problem in [our paper](https://arxiv.org/abs/2303.15933), or the minimum-weight [T-join](https://en.wikipedia.org/wiki/Chinese_postman_problem#Undirected_solution_and_T-joins) (MWTJ) problem. On the other hand, Blossom V solves the minimum-weight perfect matching (MWPM) problem. There is a reduction from MWTJ to MWPM and vice versa, hence you can use a library for one to solve the other. See our [sparse blossom paper](https://arxiv.org/abs/2303.15933) or [this comment](https://github.com/oscarhiggott/PyMatching/issues/104#issuecomment-2410208622) for more discussion on this.

Using Blossom V to solve the matching QEC decoding problem (MWTJ) is _much_ slower than sparse blossom (at least 100x slower). For example, this plot from our paper compares with pymatching v0.7, which used the [Lemon](https://lemon.cs.elte.hu/pub/doc/latest-svn/a00852.html) MWPM library to solve the decoding problem. Lemon has similar performance to Blossom V and this solution is still >100x slower than sparse blossom, even with some approximations used to improve pymatching v0.7 runtime:
<img width="620" alt="Screenshot 2024-12-31 at 11 35 28 AM" src="https://github.com/user-attachments/assets/14a9ade0-7edc-4872-9aa6-ec67ce8b72c0" />

Sparse blossom instead solves the matching QEC decoding problem directly, without the need to use a separate MWPM library (such as Blossom V or Lemon) as a subroutine.
