### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by Strilanc** [oscarhiggott/PyMatching#13]
When you're declaring a method using pybind, the define call can be given a string, which is the doc string of the method or the class. These doc strings can be viewed in editors like pycharm, or by inspecting the `__doc__` of a class or function. This is generally a pretty handy way to document methods because it gives focused help. It also gives you the opportunity to define doctest examples. Those are just short snippets of example code that you can use the doctest module to run and verify that they work.

I've also found docstrings handy for autogenerating web documentation. E.g. [stim's simple api reference page](https://github.com/quantumlib/Stim/wiki/Stim-v1.3-Python-API-Reference)  is generated by iterating over the module looking for doc strings.

**Comment by oscarhiggott** [comment]
Thanks for the tip, agree that it would be good to add these

**Comment by oscarhiggott** [comment]
This is fixed in the PyMatching v0.4.0 release
