### ISSUE TITLE
Is it possible to make  "Matching" from measurement result.

### ISSUE THREAD

**Issue by apassenger** [oscarhiggott/PyMatching#52]
Hello,

I simulated  surface code with a simulator which is different than STIM
I used distance 3 and my X stabilizers measurements are: (1, 0, 1, 1, 0, 0) and Z stabilizers measurement are (0, 1, 1, 1, 0, 1) in the absence of error for sweep 0. The repetition number of measurement for now is 1.(I can make many measurement)

In pymatching we have check_matrix structure but it is for stabilizers rather than measurement outcome of stabilizers. 
I want to plot "matching" for my measurement outcomes. How can I do that?
Or do we have a class/function/structure in pymatching that allows us to simulate/drawing matching for the measurement outcome?

**Comment by Strilanc** [comment]
You need to convert the measurement results into detection events to do matching. In stim this would be done with the `stim m2d` command (or `stim.Circuit.compile_m2d_converter`). You'll have to find the equivalent for the tool you're using.

**Comment by apassenger** [comment]
Do "detection events" mean spatial and temporal coordinates that the change occurred?
