### ISSUE TITLE
Reading b8 shot data wrong on windows (bump C++ stim dep version to 1.10)

### ISSUE THREAD

**Issue by Strilanc** [oscarhiggott/PyMatching#54]
One of the bugs fixed in stim 1.10 was that files were being opened in text mode, instead of binary mode, resulting in automatic conversion between \n and \r\n on windows. This of course completely mangles binary data, such as b8 format shot data.

Pymatching's C++ extension currently depends on stim 1.9, so it has this bug. For example, if you install the latest stim+sinter+pymatching and try to collect stats on windows, you pretty quickly run into "data has wrong size" errors.

**Comment by oscarhiggott** [comment]
The reason I hadn't updated to stim 1.10 is [this stim issue](https://github.com/quantumlib/Stim/issues/382), which we never resolved. I only encounter the issue when running pymatching tests with debug-coverage, so I _could_ just ignore it for now, use stim 1.10 and switch back locally when needed for testing.
