### ISSUE TITLE
Rename `retworkx`

### ISSUE THREAD

**Issue by quantumjim** [oscarhiggott/PyMatching#62]
The package previously known as `retworkx` is now `rustworkx`. All references in PyMatching should be updated.

**Comment by oscarhiggott** [comment]
I agree that retworkx should be replaced with rustworkx as a dependency, but the `Matching.load_from_retworkx` and `Matching.to_retworkx` methods should be kept for backward compatibility (they can try importing retworkx and use rustworkx if that fails). Then methods `Matching.load_from_rustworkx` and `Matching.to_rustworkx` could be added for rustworkx.
